# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f0074a7e32ab6c08f2b59c64922bde161bc620be5e54aa0c33bb31cb98fe18480093c7312faa8c601a885d80dcfe34fd6b6a238ed20586c777f6a6b0515769b

test:
  secret_key_base: 857f143de84bfa19cacea53ff1aabf65c2297b863d2460e734da3faf40d7e2ac0655482f5d955cad6fa0a5280ba07ba1305264085da3a08310310e58bc05d7e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
